version: '3.8'

services:
  db:
    image: postgres:15-alphine
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      -"5432:5432"
    expose:
      - 5432
    volumes:
      -postgres_data:/var/lib/postgres/data

volumes:
  postgres_data